App\Entity\Furniture:
  attributes:
    id:
      groups: [ 'item:output', 'collection:output' ]
    furnitureType:
      groups: [ 'item:output', 'collection:output', 'create:input' ]
    points:
      groups: [ 'item:output', 'collection:output', 'create:input' ]
    nonClearanceSide:
      groups: [ 'item:output', 'collection:output', 'create:input' ]
    openToSide:
      groups: [ 'item:output', 'collection:output', 'create:input' ]
