App\Entity\Resource:
  attributes:
    id:
      groups: [ 'resourceItem:output', 'resourceCollection:output', 'resourceCreate:input', 'resourceUpdate:input' ]
    ip:
      groups: [ 'resourceItem:output', 'resourceCollection:output', 'resourceCreate:input', 'resourceUpdate:input' ]
    name:
      groups: [ 'resourceItem:output', 'resourceCollection:output', 'resourceCreate:input', 'resourceUpdate:input' ]
    owner:
      groups: [ 'resourceItem:output', 'resourceCollection:output', 'resourceCreate:input', 'resourceUpdate:input' ]
    description:
      groups: [ 'resourceItem:output', 'resourceCollection:output', 'resourceCreate:input', 'resourceUpdate:input' ]
    creationDate:
      groups: [ 'resourceItem:output', 'resourceCollection:output' ]
