App\Entity\User:
  attributes:
    id:
      groups: [ 'login:output', 'item:output', 'collection:output', 'create:input' ]
    email:
      groups: [ 'login:output', 'item:output', 'collection:output', 'create:input' ]
    roles:
      groups: [ 'login:output', 'item:output', 'collection:output', 'create:input' ]
    username:
      groups: [ 'login:output', 'item:output', 'collection:output', 'create:input' ]
    room:
      groups: [ 'login:output', 'item:output', 'collection:output', 'create:input' ]
    plainPassword:
      groups: [ 'create:input' ]
    active:
      groups: [ 'create:input' ]
