App\Entity\User:
  attributes:
    id:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    email:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    roles:
      groups: [ 'login:output', 'item:output', 'create:input' ]
    username:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    firstName:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    lastName:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    birthDate:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input' ]
    room:
      groups: [ 'login:output', 'item:output', 'user_collection:output', 'create:input', 'update:input' ]
    active:
      groups: [ 'create:input', 'item:output', 'user_collection:output', 'update:input' ]
    plainPassword:
      groups: [ 'create:input', 'update:input' ]
    oldPassword:
      groups: [ 'update:input' ]
