App\Entity\User:
  properties:
    id:
      identifier: true
  collectionOperations:
    get:
      filters: ['user.roomFilter']
      normalization_context:
        groups: [ 'user_collection:output' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
      denormalization_context:
        groups: [ 'create:input' ]

  itemOperations:
    get:
      normalization_context:
        groups: [ 'item:output' ]
    patch:
      security: 'is_granted("ROLE_ADMIN")'
      denormalization_context:
        groups: [ 'update:input' ]
    delete:
      security: 'is_granted("ROLE_ADMIN")'

  graphql:
    collection_query:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: [ 'collection:output' ]
    item_query:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: [ 'item:output' ]
