api_login_check:
  path: /login
api_token_refresh:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation
